flowchart TD

    run_atmofs03["atmofs03<br/>train<br/>pre-train"]
    run_rqcsy7ze["rqcsy7ze<br/>inference<br/>1y-rollout"]
    run_xuwd4y83["xuwd4y83<br/>train<br/>avg-dt"]
    run_vm3b5wyi["vm3b5wyi<br/>train<br/>avg-dt"]
    run_tdc93mxn["tdc93mxn<br/>train<br/>avg-dt"]
    run_e3xvz4yi["e3xvz4yi<br/>fine-tune<br/>avg-dt"]
    run_yxvpt9ng["yxvpt9ng<br/>fine-tune<br/>avg-dt"]
    run_svuxthgo["svuxthgo<br/>fine-tune<br/>avg-dt"]
    run_eb5fdypv["eb5fdypv<br/>inference<br/>avg-dt"]
    run_hblhjk7s["hblhjk7s<br/>inference<br/>avg-dt"]
    run_lhqu759o["lhqu759o<br/>inference<br/>avg-dt"]
    run_x38glzpu["x38glzpu<br/>evaluate<br/>avg-dt"]

    run_atmofs03 --> run_rqcsy7ze
    run_xuwd4y83 --> run_e3xvz4yi
    run_vm3b5wyi --> run_yxvpt9ng
    run_tdc93mxn --> run_svuxthgo
    run_xuwd4y83 --> run_eb5fdypv
    run_vm3b5wyi --> run_hblhjk7s
    run_tdc93mxn --> run_lhqu759o
    run_atmofs03 --> run_x38glzpu
    run_tdc93mxn --> run_x38glzpu
    run_hblhjk7s --> run_x38glzpu

    class run_atmofs03 type_train;
    class run_atmofs03 category_pre_train;
    class run_rqcsy7ze type_inference;
    class run_rqcsy7ze category_1y_rollout;
    class run_xuwd4y83 type_train;
    class run_xuwd4y83 category_avg_dt;
    class run_vm3b5wyi type_train;
    class run_vm3b5wyi category_avg_dt;
    class run_tdc93mxn type_train;
    class run_tdc93mxn category_avg_dt;
    class run_e3xvz4yi type_fine_tune;
    class run_e3xvz4yi category_avg_dt;
    class run_yxvpt9ng type_fine_tune;
    class run_yxvpt9ng category_avg_dt;
    class run_svuxthgo type_fine_tune;
    class run_svuxthgo category_avg_dt;
    class run_eb5fdypv type_inference;
    class run_eb5fdypv category_avg_dt;
    class run_hblhjk7s type_inference;
    class run_hblhjk7s category_avg_dt;
    class run_lhqu759o type_inference;
    class run_lhqu759o category_avg_dt;
    class run_x38glzpu type_evaluate;
    class run_x38glzpu category_avg_dt;

    classDef type_fine_tune fill:#e3f2fd,stroke:#1565c0,stroke-width:2px;
    classDef type_inference fill:#fff8e1,stroke:#f9a825,stroke-width:2px;
    classDef type_train fill:#e8f5e9,stroke:#2e7d32,stroke-width:2px;
    classDef category_1y_rollout stroke-width:4px;
    classDef category_avg_dt stroke-dasharray:5 5;
